### ISSUE TITLE
RC库中是不是缺少RES_0603的PCB封装？

### ISSUE THREAD

**Issue by guohaomeng** [AstraThreshold/AltiumDesignerLibPkg-dream#2]
如图：

<img width="197" alt="image" src="https://github.com/forpaindream/AltiumDesignerLibPkg-dream/assets/44870854/4b2dd7cc-425d-43a9-8af7-9090e58725de">

**Comment by AstraThreshold** [comment]
是的，因为项目中并未用到过0603电阻，可暂时用0603电容替代/自行填补/等待我版本更新
